language: node_js

node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
before_deploy:
  - npm install netlify-cli -g
deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=dist --prod
  on:
    branch: master
